---
# handlers for haproxy_lb

- name: restart haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted

- name: reload haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded

- name: restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
