---
# Grafana Handlers
# Author: HyHonCuTe

- name: restart grafana
  systemd:
    name: grafana-server
    state: restarted
    daemon_reload: yes

- name: reload grafana
  systemd:
    name: grafana-server
    state: reloaded
